services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edgefl-app
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "run.py"]
    depends_on:
      - mlflow
      - pushgateway

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.10.0
    container_name: mlflow
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri /mlflow --default-artifact-root /mlflow/artifacts
    ports: ["5000:5000"]
    volumes:
      - ./docker/mlflow:/mlflow

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports: ["9091:9091"]

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports: ["9090:9090"]
    depends_on: [pushgateway]

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports: ["3000:3000"]
    depends_on: [prometheus]
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
